### ISSUE TITLE
Where does one set the start- and endRegionWord??

### ISSUE THREAD

**Issue by rblinzler2** [thehogfather/brackets-custom-region-code-folding#12]
Where does one set the start- and endRegionWord??

**Comment by ekk-amboss** [comment]
in the file .brackets.json located in your brackets folder.

**Comment by thehogfather** [comment]
@rblinzler2 you can set it in your project preference file (i.e., `.brackets.json` at the root of your project) as pointed out by @ekk-amboss. 

Or you can set it globally in the `brackets.json` file (found by clicking `Debug` -> `Open Preferene File`)

**Comment by rblinzler2** [comment]
Ok, found it in the AppData\Roaming\Brackets folder.
Thx.
