### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by tatof** [thehogfather/brackets-custom-region-code-folding#2]
Hello,

First of all great plugin! use it at home without problems and its awesome for CSS folding!
Only on an other computer: When installing your plugin it gives an "Extension error".

When I download it from github there is no change in the problem.
Any ideas?

**Comment by thehogfather** [comment]
Can you give a detailed description of the OS, and Brackets version you have installed?

**Comment by tatof** [comment]
Windows 7 x64 Professional, Brackets sprint build 1.3.0-16022 - build Apr 24 2015
not working there.

Windows 7 x64 ultimate, Brackets (older version)
Works fine, (perfect)

**Comment by tatof** [comment]
Windows 7 x64 Professional, Brackets sprint build 1.3.0-16022 - build Apr
24 2015

Met vriendelijke groet,

Jesse Bakker

*Tatof* - *Online Solutions*

www.tatof.nl  <http://www.tatof.nl/>
info@tatof.nl
06 121 286 81

**Comment by tatof** [comment]
how to fix this with english language strings.js?

My system language is "dutch" and at home its "english". 
So yes this could be the problem.

**Comment by nightsinnight** [comment]
Please try it.

1.Start Brakets and select "Show Developer tools" from Debug menu.
2.Select "Console" tab in Developer tools.
3.Select "Reload with Extensions." from Brackets' Debug menu.

What do console output?
in my env, console outputs,
"Uncaught Error: Script error for: nls/ja/strings".
so, I created in nls/ja/string.json, all is OK.

**Comment by thehogfather** [comment]
Sorry for the late response. @tatof @nightsinnight could you install from github master and see if the issue is still present?

**Comment by nightsinnight** [comment]
@thehogfather in my env, It's working well. thx.

**Comment by tatof** [comment]
I will try this and post my findings as fast as posible! thanks :)

**Comment by tatof** [comment]
sorry for the long wait! but downloading from here and the plugin works fine! thanks :D
