### ISSUE TITLE
[Suggestion] Hide the words 'Region/Endregion' on collapse

### ISSUE THREAD

**Issue by NickGrease** [thehogfather/brackets-custom-region-code-folding#4]
First let me say thanks for this extension, use it all the time. Second, I'm new to Git and Brackets, if this isn't the right place for suggestions, or what I'm asking for isn't possible, you have my apologies.

It's been a while since I used Visual Studio, but if I remember correctly, when collapsing a custom region, all that would be visible were the word(s) after //region. So if you folded:

```
//region My Custom Region
...
//endregion
```

you would just see:

```
My Custom Region [...]
```

If that makes sense. As an added bonus, any chance  the 'region title' could be colored (again, like VS)?

**Comment by shaneparsons** [comment]
**+1** -  I think this would be a great feature, and would help keep code as tidy as possible.. especially with multiple custom regions per page.

I personally don't need the 'region title colouring'.. but that's just me.

**Comment by thehogfather** [comment]
This can certainly be sorted in the next update.

**Comment by foice** [comment]
Sound like a great addition indeed

**Comment by thehogfather** [comment]
Assuming `region` and `endregion` are your keywords, now you can have

```
 //My Custom Label region
 ---
 //endregion
```

and you would just see:

```
My Custom Label [...]
```

**Comment by shaneparsons** [comment]
Perfect, thanks!

**Comment by NickGrease** [comment]
Much appreciated!
