### ISSUE TITLE
Does it work with languages whose syntax coloring extension is based on CodeMirror SimpleMode?

### ISSUE THREAD

**Issue by foice** [thehogfather/brackets-custom-region-code-folding#6]
Hello
 I have successfully installed this beautiful extension, which adds really a great feature. Thanks for developing it.

I can have it to work properly on "standard" languages. For instance if I put
    # region REG
    My
    region
    to
    be
    folded
    away
    # endregion

in README.md of this extension (just for a try), the file is recognized as Markdown and I get the little triangle on the left to fold the code.

The same code, however, does not work on files that are colored according to a (non published) extension based on SimpleCode that I made myself. Comments (based on # in my language as well) are properly understood in my extension, as far as I can tell, but I do not get the triangle to fold the code.

Any idea why?

**Comment by thehogfather** [comment]
The only reason I can think of is that the mode might not be setting the `comment` type on a token that is a comment. But that is merely speculation. Could you post a link to your mode and I can test it? It might be a bug in my extension.

**Comment by foice** [comment]
With pleasure, but how should I post this file? I am not familiar with GitHub at all ...

**Comment by thehogfather** [comment]
easiest way would be to create a git repository for your project, push it to github and I can have a look at that. Github has nice steps regarding how to push your projects when you create a repository.

**Comment by foice** [comment]
This is the extension main.js file
https://github.com/foice/human-color-syntax/blob/master/human/main.js
and a sample file it is supposed to color
https://github.com/foice/human-color-syntax/blob/master/human/example.human

PS
I should add that `##` gives some problem in the coloring, because I suppose I did not code well the regexp for the comments being anything following a `#`. However, as long as the file does not have `##` should be fine. Note that `###` are ok.

**Comment by thehogfather** [comment]
I've created a PR here https://github.com/foice/human-color-syntax/pull/1
There was an issue with your mode.
